import type { Metadata } from "next";
import { Abril_Fatface } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import ClientProvider from "@/providers/ClientProvider";
import MobileHeader from "@/components/MobileHeader";

const abril = Abril_Fatface({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={abril.className}>
        <ClientProvider>
          <Header />
          <MobileHeader />
          {children}
          <Footer />
        </ClientProvider>
      </body>
    </html>
  );
}
