/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 earth.gltf 
Author: PatelDev (https://sketchfab.com/PatelDev)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/earth-f7a76c63ff1846afb2d606e5c8369c15
Title: Earth
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export default function EarthModel(props, { scale, position, rotation }) {
  const { nodes, materials } = useGLTF("/earth/earth.gltf");

  const modelRef = useRef();

  useFrame((state) => {
    modelRef.current.position.y =
      -1.5 + Math.sin(state.clock.elapsedTime) * 0.15;

    modelRef.current.rotation.y = Math.sin(state.clock.elapsedTime);
  });

  return (
    <group {...props} dispose={null} ref={modelRef}>
      <mesh
        castShadow
        receiveShadow
        position={position ? position : [0, 1.5, 0]}
        rotation={rotation ? rotation : [0.3, 0, 0]}
        scale={scale ?? 1.8}
        geometry={nodes.Object_4.geometry}
        material={materials["Scene_-_Root"]}
      />
    </group>
  );
}

useGLTF.preload("/earth/earth.gltf");
